language: generic

sudo: required

services:
    - docker

after_success:
    - docker build -t constwon111/blued-frontend ./client
    - docker build -t constwon111/blued-backend ./server
    - docker build -t constwon111/blued-nginx ./nginx

    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

    - docker push constwon111/blued-frontend
    - docker push constwon111/blued-backend
    - docker push constwon111/blued-nginx
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker-blued-donation"
    env: "Dockerblueddonation-env"
    bucket_name: elasticbeanstalk-us-east-1-250552661696
    bucket_path: "docker-blued-donation"
    on:
        branch: main

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
