version: "3"
services:
    client:
        image: constwon111/blued-frontend
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true

    nginx:
        restart: always
        image: constwon111/blued-nginx
        ports:
            - "80:80"

    server:
        image: constwon111/blued-backend
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            MYSQL_HOST: $MYSQL_HOST
            MYSQL_USER: $MYSQL_USER
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_PORT: $MYSQL_PORT

    # mysql:
    #     build: ./mysql
    #     restart: unless-stopped
    #     container_name: blued_mysql
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql/mysql_data:/var/lib/mysql
    #         - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    #     environment:
    #         MYSQL_ROOT_PASSWORD: tndtlf98
    #         MYSQL_DATABASE: blued_donation
