version: "2.4"
services:
    client:
        image: constwon111/blued-frontend
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true
        mem_limit: 128m

    nginx:
        restart: always
        image: constwon111/blued-nginx
        ports:
            - "80:80"
        mem_limit: 128m
        links:
            - client
            - server

    server:
        image: constwon111/blued-backend
        volumes:
            - /app/node_modules
            - ./server:/app
        mem_limit: 128m
        environment:
            MYSQL_HOST: docker-blued-mysql.ctkxqf6wope7.us-east-1.rds.amazonaws.com
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: tndtlf98
            MYSQL_DATABASE: blued_donation
            MYSQL_PORT: 3306

    # mysql:
    #     build: ./mysql
    #     restart: unless-stopped
    #     container_name: blued_mysql
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql/mysql_data:/var/lib/mysql
    #         - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    #     environment:
    #         MYSQL_ROOT_PASSWORD: tndtlf98
    #         MYSQL_DATABASE: blued_donation
