version: "3"
services:
    frontend:
        image: constwon111/blued-frontend
        volumes:
            - /app/node_modules
            - ./client:/app
        stdin_open: true
        mem_limit: 128m

    nginx:
        restart: always
        image: constwon111/blued-nginx
        ports:
            - "80:80"

    backend:
        image: constwon111/blued-backend
        container_name: blued_backend
        volumes:
            - /app/node_modules
            - ./server:/app
        mem_limit: 128m
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: constwon111
            MYSQL_DATABASE: myapp
            MYSQL_PORT: 3306

    # mysql:
    #     build: ./mysql
    #     restart: unless-stopped
    #     container_name: blued_mysql
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - ./mysql/mysql_data:/var/lib/mysql
    #         - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    #     environment:
    #         MYSQL_ROOT_PASSWORD: constwon111
    #         MYSQL_DATABASE: blued_donation
