FROM node:14.14.0-alpine

WORKDIR /app

COPY ./package.json ./

RUN npm install
# RUN git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StricHostKeyChecking=no'

COPY . .

CMD ["npm", "run", "dev"]

